<script setup>
// ========================================
// CrudTest.vue - Frontend Component
// ========================================
// This Vue component provides a CRUD interface for the Test entity.
// It communicates with the Spring Boot backend via TestService.
//
// Connection Flow:
// 1. Frontend Form → TestService (client/src/service/TestService.js)
// 2. TestService → HTTP requests to /api/tests endpoint
// 3. Backend /api/tests → TestController (Spring Boot REST controller)
// 4. TestController → TestService (Java service layer)
// 5. TestService → TestRepository (JPA - communicates with database)
// 6. Database → Test entity (JPA-mapped to 'test' table in PostgreSQL)
// ========================================

import { FilterMatchMode } from 'primevue/api';
import { ref, onMounted, onBeforeMount } from 'vue';
import TestService from '@/service/TestService'; // Client service that talks to /api/tests
import { useToast } from 'primevue/usetoast'; // Toast notifications for user feedback

const toast = useToast();

// ========================================
// Reactive State - Binds to Frontend UI
// ========================================
// These variables control what the user sees and interacts with in the form.
// They are bound to the template using v-model directives.

// Main data list: Fetches from Spring Backend GET /api/tests
// Maps to Test entity fields: id, text1, size
const tests = ref([]);

// Dialog visibility flags - control which modal windows are shown
const testDialog = ref(false); // Create/Edit form dialog
const deleteTestDialog = ref(false); // Delete confirmation dialog
const deleteTestsDialog = ref(false); // Batch delete confirmation dialog

// Currently selected test object for editing or deletion
// Structure matches Test entity from backend:
// {
//   id: Long (auto-generated by database),
//   text1: String (text field),
//   size: Integer (numeric field)
// }
const test = ref({});

const selectedTests = ref(null); // Multiple tests selected for batch delete
const dt = ref(null); // Reference to DataTable for CSV export
const filters = ref({}); // Search/filter state
const submitted = ref(false); // Track if form has been submitted (for validation)

// Create an instance of TestService to make API calls
const testService = new TestService();

// ========================================
// CONFIGURATION - Define entity fields
// ========================================
// This configuration array drives both table columns and form fields.
// Modify this single array to change the UI without touching template code.
//
// Field properties:
//   - name: Property name in the Test object (must match backend field)
//   - label: Display name shown to users
//   - type: Input type (text, number, textarea, date, etc.)
//   - sortable: Allow table sorting on this column
//   - displayInTable: Show this field as a table column
//   - displayInForm: Show this field in the edit/create form
//   - editable: Allow editing (false for read-only like id)
//   - required: Validate that field is not empty
//   - width: Column width for table and form layout
const formConfig = [
    {
        name: 'id',
        label: 'ID',
        type: 'text',
        sortable: true,
        displayInTable: true,
        displayInForm: true,
        editable: false,
        required: false,
        width: '10%'
    },
    {
        name: 'text1',
        label: 'Text',
        type: 'text',
        sortable: true,
        displayInTable: true,
        displayInForm: true,
        editable: true,
        required: true,
        width: '40%'
    },
    {
        name: 'size',
        label: 'Size',
        type: 'number',
        sortable: true,
        displayInTable: true,
        displayInForm: true,
        editable: true,
        required: true,
        width: '20%'
    }
];

// ========================================
// Lifecycle Hooks
// ========================================
// These run when the component mounts (appears on screen)

onBeforeMount(() => {
    initFilters();
});

onMounted(() => {
    loadTests(); // Fetch all tests from backend when component loads
});

// ========================================
// READ - Fetch all tests from backend
// ========================================
// Calls TestService.getTests() → HTTP GET /api/tests
// Backend: TestController.getAllTests() returns List<Test>
// Response: Array of test objects with id, text1, size
// Updates: tests.value with the list from database
const loadTests = () => {
    testService.getTests().then((data) => (tests.value = data));
};

// ========================================
// CREATE/EDIT Dialog - Open form
// ========================================
// Opens the dialog for creating a new test (empty form)
const openNew = () => {
    test.value = {}; // Clear the form
    submitted.value = false; // Reset validation
    testDialog.value = true; // Show the dialog
};

const hideDialog = () => {
    testDialog.value = false;
    submitted.value = false;
};

// ========================================
// CREATE (POST) or UPDATE (local) - Save test
// ========================================
// This method handles both creating NEW tests and updating EXISTING tests.
// 
// For NEW tests (no id):
//   1. Validates form using formConfig.required fields
//   2. Calls TestService.createTest(test.value) → HTTP POST /api/tests
//   3. Backend: TestController.createTest(@RequestBody Test test)
//   4. Backend: TestService.save(test) → TestRepository.save(test)
//   5. Database: JPA @Entity Test is persisted, id auto-generated
//   6. Response: Newly created test with id
//   7. Frontend: Adds to local tests.value array
//
// For EXISTING tests (has id):
//   NOTE: Currently this only updates locally. To fully implement:
//   - Add PUT/PATCH endpoint in TestController
//   - Call testService.updateTest(test.value)
//   - Backend would do: testRepository.save(test) which updates if id exists
const saveTest = async () => {
    submitted.value = true;

    // Dynamic validation based on formConfig
    // Check all required fields are filled
    const isValid = formConfig.every((field) => {
        if (field.required && field.editable) {
            const value = test.value[field.name];
            if (typeof value === 'string') {
                return value && value.trim() !== '';
            }
            return value != null;
        }
        return true;
    });

    if (isValid) {
        if (test.value.id) {
            // UPDATE case (currently local only)
            const index = findIndexById(test.value.id);
            tests.value[index] = { ...test.value };
            toast.add({ severity: 'success', summary: 'Successful', detail: 'Test Updated', life: 3000 });
        } else {
            // CREATE case - sends to backend
            const createdTest = await testService.createTest(test.value);
            tests.value.push(createdTest); // Add server response (with id) to list
            toast.add({ severity: 'success', summary: 'Successful', detail: 'Test Created', life: 3000 });
        }

        testDialog.value = false;
        test.value = {};
    }
};

// ========================================
// UTILITY - Get editable fields for form
// ========================================
// Returns only fields that should appear in the form
const getEditableFields = () => {
    return formConfig.filter((field) => field.displayInForm);
};

// ========================================
// UTILITY - Get table fields
// ========================================
// Returns only fields that should appear in the table
const getTableFields = () => {
    return formConfig.filter((field) => field.displayInTable);
};

// ========================================
// UTILITY - Check if field is required and has error
// ========================================
const hasFieldError = (fieldName) => {
    const field = formConfig.find((f) => f.name === fieldName);
    return submitted.value && field?.required && !test.value[fieldName];
};

// ========================================
// READ - Load test for editing
// ========================================
// When user clicks the edit (pencil) button on a row:
// 1. This method is called with the test object (id, text1, size)
// 2. Copies the test into the form
// 3. Opens the dialog to allow edits
const editTest = (selectedTest) => {
    test.value = { ...selectedTest }; // Copy object for editing
    testDialog.value = true;
};

// ========================================
// DELETE - Confirm deletion (show dialog)
// ========================================
// When user clicks the delete (trash) button on a row:
// Shows a confirmation dialog before actually deleting
const confirmDeleteTest = (selectedTest) => {
    test.value = selectedTest; // Load test into memory for deletion
    deleteTestDialog.value = true; // Show confirmation dialog
};

// ========================================
// DELETE (HTTP DELETE) - Persist deletion to backend
// ========================================
// When user confirms deletion:
// 1. Calls TestService.deleteTest(id) → HTTP DELETE /api/tests/{id}
// 2. Backend: TestController.deleteTest(@PathVariable Long id)
// 3. Backend: TestService.deleteById(id) → TestRepository.deleteById(id)
// 4. Database: JPA removes the Test record with matching id
// 5. Frontend: Removes from local tests.value array
const deleteTest = async () => {
    await testService.deleteTest(test.value.id); // Call backend DELETE endpoint
    tests.value = tests.value.filter((val) => val.id !== test.value.id); // Update UI
    deleteTestDialog.value = false;
    test.value = {};
    toast.add({ severity: 'success', summary: 'Successful', detail: 'Test Deleted', life: 3000 });
};

// ========================================
// UTILITY - Find test by id
// ========================================
// Helper function to locate a test object in the array by its primary key (id)
const findIndexById = (id) => {
    let index = -1;
    for (let i = 0; i < tests.value.length; i++) {
        if (tests.value[i].id === id) {
            index = i;
            break;
        }
    }
    return index;
};

// ========================================
// DELETE Multiple - Batch deletion (show confirmation)
// ========================================
// When user clicks the "Delete" button in toolbar with multiple rows selected:
// Shows confirmation dialog before batch delete
const confirmDeleteSelected = () => {
    deleteTestsDialog.value = true;
};

// ========================================
// DELETE Multiple (HTTP DELETE) - Batch deletion to backend
// ========================================
// When user confirms batch deletion:
// 1. For each selected test, calls TestService.deleteTest(id)
// 2. Backend deletes each test record from database
// 3. Frontend removes all deleted tests from tests.value array
const deleteSelectedTests = async () => {
    if (selectedTests.value && selectedTests.value.length) {
        // Promise.all waits for all delete requests to complete
        await Promise.all(selectedTests.value.map((item) => testService.deleteTest(item.id)));
        tests.value = tests.value.filter((val) => !selectedTests.value.includes(val));
        deleteTestsDialog.value = false;
        selectedTests.value = null;
        toast.add({ severity: 'success', summary: 'Successful', detail: 'Tests Deleted', life: 3000 });
    }
};

// ========================================
// Initialize Filters
// ========================================
// Sets up the global search filter configuration for the data table
const initFilters = () => {
    filters.value = {
        global: { value: null, matchMode: FilterMatchMode.CONTAINS }
    };
};
</script>

<template>
    <!-- ========================================
         TABLE - Displays all tests fetched from backend
         ======================================== -->
    <div class="grid">
        <div class="col-12">
            <div class="card">
                <Toast />
                <Toolbar class="mb-4">
                    <template v-slot:start>
                        <div class="my-2">
                            <!-- "New" button opens empty form to CREATE a test -->
                            <Button label="New" icon="pi pi-plus" class="p-button-success mr-2" @click="openNew" />
                            <!-- "Delete" button shows batch delete dialog for selected tests -->
                            <Button label="Delete" icon="pi pi-trash" class="p-button-danger" @click="confirmDeleteSelected" :disabled="!selectedTests || !selectedTests.length" />
                        </div>
                    </template>
                </Toolbar>

                <!-- DataTable: Renders all tests from the backend -->
                <!-- :value="tests" - Binds to the reactive tests array (fetched from /api/tests) -->
                <!-- v-model:selection="selectedTests" - Tracks which rows user selected -->
                <DataTable
                    ref="dt"
                    :value="tests"
                    v-model:selection="selectedTests"
                    dataKey="id"
                    :paginator="true"
                    :rows="10"
                    :filters="filters"
                    paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                    :rowsPerPageOptions="[5, 10, 25]"
                    currentPageReportTemplate="Showing {first} to {last} of {totalRecords} records"
                    responsiveLayout="scroll"
                >
                    <template #header>
                        <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                            <h5 class="m-0">Manage Records</h5>
                            <!-- Global search box - filters by all displayable fields -->
                            <span class="block mt-2 md:mt-0 p-input-icon-left">
                                <i class="pi pi-search" />
                                <InputText v-model="filters['global'].value" placeholder="Search..." />
                            </span>
                        </div>
                    </template>

                    <!-- Checkbox column - allows multi-select for batch operations -->
                    <Column selectionMode="multiple" headerStyle="width: 3rem"></Column>

                    <!-- DYNAMIC COLUMNS - Generated from formConfig -->
                    <!-- Each field with displayInTable=true becomes a table column -->
                    <Column 
                        v-for="field in getTableFields()" 
                        :key="field.name"
                        :field="field.name" 
                        :header="field.label" 
                        :sortable="field.sortable"
                        :headerStyle="`width:${field.width}; min-width:8rem;`"
                    >
                        <template #body="slotProps">
                            <span class="p-column-title">{{ field.label }}</span>
                            {{ slotProps.data[field.name] }}
                        </template>
                    </Column>

                    <!-- Action Buttons Column -->
                    <Column headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <!-- Edit button - opens dialog to UPDATE record -->
                            <Button icon="pi pi-pencil" class="p-button-rounded p-button-success mr-2" @click="editTest(slotProps.data)" />
                            <!-- Delete button - opens confirmation dialog to DELETE record -->
                            <Button icon="pi pi-trash" class="p-button-rounded p-button-warning mt-2" @click="confirmDeleteTest(slotProps.data)" />
                        </template>
                    </Column>
                </DataTable>

                <!-- ========================================
                     FORM DIALOG - Create or Edit a Record
                     ======================================== -->
                <!-- v-model:visible="testDialog" - Controls when dialog appears/disappears -->
                <Dialog v-model:visible="testDialog" :style="{ width: '600px' }" header="Record Details" :modal="true" class="p-fluid">
                    
                    <!-- DYNAMIC FORM FIELDS - Generated from formConfig -->
                    <!-- Each field with displayInForm=true becomes a form input -->
                    <template v-for="field in getEditableFields()" :key="field.name">
                        
                        <!-- READ-ONLY FIELD (e.g., auto-generated ID) -->
                        <div v-if="!field.editable" class="field">
                            <label :for="field.name">{{ field.label }}</label>
                            <InputText 
                                :id="field.name"
                                :modelValue="test[field.name]"
                                disabled
                            />
                        </div>

                        <!-- TEXT INPUT FIELD -->
                        <div v-else-if="field.type === 'text'" class="field">
                            <label :for="field.name">{{ field.label }}</label>
                            <InputText 
                                :id="field.name"
                                v-model.trim="test[field.name]"
                                autofocus
                                :class="{ 'p-invalid': hasFieldError(field.name) }"
                            />
                            <small v-if="hasFieldError(field.name)" class="p-invalid">
                                {{ field.label }} is required.
                            </small>
                        </div>

                        <!-- NUMBER INPUT FIELD -->
                        <div v-else-if="field.type === 'number'" class="field">
                            <label :for="field.name">{{ field.label }}</label>
                            <InputNumber 
                                :id="field.name"
                                v-model="test[field.name]"
                                integeronly
                                :class="{ 'p-invalid': hasFieldError(field.name) }"
                            />
                            <small v-if="hasFieldError(field.name)" class="p-invalid">
                                {{ field.label }} is required.
                            </small>
                        </div>

                        <!-- TEXTAREA FIELD -->
                        <div v-else-if="field.type === 'textarea'" class="field">
                            <label :for="field.name">{{ field.label }}</label>
                            <Textarea 
                                :id="field.name"
                                v-model="test[field.name]"
                                rows="3"
                                cols="20"
                                :class="{ 'p-invalid': hasFieldError(field.name) }"
                            />
                            <small v-if="hasFieldError(field.name)" class="p-invalid">
                                {{ field.label }} is required.
                            </small>
                        </div>

                        <!-- DATE INPUT FIELD -->
                        <div v-else-if="field.type === 'date'" class="field">
                            <label :for="field.name">{{ field.label }}</label>
                            <Calendar 
                                :id="field.name"
                                v-model="test[field.name]"
                                :class="{ 'p-invalid': hasFieldError(field.name) }"
                            />
                            <small v-if="hasFieldError(field.name)" class="p-invalid">
                                {{ field.label }} is required.
                            </small>
                        </div>

                    </template>

                    <!-- Dialog Footer -->
                    <template #footer>
                        <Button label="Cancel" icon="pi pi-times" class="p-button-text" @click="hideDialog" />
                        <!-- Save button calls saveTest() which validates and sends POST/PUT to backend -->
                        <Button label="Save" icon="pi pi-check" class="p-button-text" @click="saveTest" />
                    </template>
                </Dialog>

                <!-- ========================================
                     DELETE CONFIRMATION DIALOG - Single delete
                     ======================================== -->
                <Dialog v-model:visible="deleteTestDialog" :style="{ width: '450px' }" header="Confirm" :modal="true">
                    <div class="flex align-items-center justify-content-center">
                        <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                        <span v-if="test">
                            Are you sure you want to delete this record?
                        </span>
                    </div>
                    <template #footer>
                        <Button label="No" icon="pi pi-times" class="p-button-text" @click="deleteTestDialog = false" />
                        <!-- Yes button calls deleteTest() which sends HTTP DELETE to backend -->
                        <Button label="Yes" icon="pi pi-check" class="p-button-text" @click="deleteTest" />
                    </template>
                </Dialog>

                <!-- ========================================
                     DELETE CONFIRMATION DIALOG - Batch delete
                     ======================================== -->
                <Dialog v-model:visible="deleteTestsDialog" :style="{ width: '450px' }" header="Confirm" :modal="true">
                    <div class="flex align-items-center justify-content-center">
                        <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                        <span>Are you sure you want to delete the selected records?</span>
                    </div>
                    <template #footer>
                        <Button label="No" icon="pi pi-times" class="p-button-text" @click="deleteTestsDialog = false" />
                        <!-- Yes button calls deleteSelectedTests() which sends multiple HTTP DELETE requests -->
                        <Button label="Yes" icon="pi pi-check" class="p-button-text" @click="deleteSelectedTests" />
                    </template>
                </Dialog>
            </div>
        </div>
    </div>
</template>

<style scoped lang="scss"></style>
