services:
  postgres:
    image: postgres:latest
    container_name: saavy_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: saavy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - saavy_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
     build:
       context: .
       dockerfile: server/DockerFile
     container_name: saavy_app
     environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/saavy_db
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: password
     ports:
       - "8080:8080"
     depends_on:
       postgres:
         condition: service_healthy
     networks:
       - saavy_network

volumes:
  postgres_data:

networks:
  saavy_network:
    driver: bridge
