spring.application.name=SaavySpringBootVue

# PostgreSQL database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/saavy_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

