# Build stage
FROM eclipse-temurin:21-jdk-jammy AS build
COPY . .
RUN chmod +x ./server/gradlew
RUN ./server/gradlew bootJar --no-daemon

FROM eclipse-temurin:21-jre-jammy

COPY --from=build /build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]
