FROM eclipse-temurin:21-jdk-jammy AS build
WORKDIR /app
COPY . .
COPY ./client/.env.production /app/client/.env
# Set VITE_SERVER_URL to new value
ENV VITE_SERVER_URL ${VITE_SERVER_URL}
RUN chmod +x ./server/gradlew && ./server/gradlew bootJar --no-daemon

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/server/build/libs/server-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar","--spring.profiles.active=production"]
